package org.netbeans.modules.idf;

/**
 *
 * @author gwieleng
 */
public class PreviewPanel extends javax.swing.JPanel {

    /**
     * Creates new form PreviewPanel
     */
    public PreviewPanel() {
        initComponents();
        jEditorPane1.setText("import java.awt.event.ActionEvent;\n" +
"import java.awt.event.ActionListener;\n" +
"\n" +
"public class ClassA implements ActionListener, Runnable {\n" +
"\n" +
"    //After sorting, \n" +
"    //this method will be displayed second,\n" +
"    //since its interface is second in the class signature:\n" +
"    @Override\n" +
"    public void run() {\n" +
"    }\n" +
"    \n" +
"    //After sorting, \n" +
"    //this method will be displayed first,\n" +
"    //since its interface is first in the class signature:\n" +
"    @Override\n" +
"    public void actionPerformed(ActionEvent e) {\n" +
"    }\n" +
"    \n" +
"}\n" +
"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        jScrollPane2.setEnabled(false);

        jEditorPane1.setContentType("text/x-java"); // NOI18N
        jScrollPane2.setViewportView(jEditorPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
